services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery-worker:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command: celery -A app worker --loglevel=info --queues=default,slots
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development

  celery-beat:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command: celery -A app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development

volumes:
  redis-data: