services:
  app:
    build:
      context: .
      args:
        - DEV=true
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app


  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for faster tests

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery-worker:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command: celery -A app worker --loglevel=info --queues=default,slots
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development

  celery-beat:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command: celery -A app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development

volumes:
  redis-data: