version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DEV=false
    container_name: kmdiscova-api-prod
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    # Use the entrypoint script instead of complex command
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin123456
      - HTTPS_ENABLED=True
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - kmdiscova-network

  nginx:
    image: nginx:alpine
    container_name: kmdiscova-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - kmdiscova-network

  certbot:
    image: certbot/certbot
    container_name: kmdiscova-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

networks:
  kmdiscova-network:
    driver: bridge

volumes:
  static_volume:
  media_volume: