services:
  app:
    build:
      context: .
      args:
        - DEV=false
    container_name: kmdiscova-app-debug
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             echo 'Testing Django startup...' &&
             python manage.py check --deploy &&
             echo 'Django check passed! Starting runserver...' &&
             python manage.py runserver 0.0.0.0:8000 --settings=app.settings.production"
    env_file:
      - .env.prod
    restart: "no"
    networks:
      - kmdiscova-prod

networks:
  kmdiscova-prod:
    driver: bridge
volumes:
  static_volume:
  media_volume: