version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DEV=false
    container_name: kmdiscova-api-prod
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             # The createsuperuser command can be problematic in automated deployments.
             # Consider creating users via initial data fixtures or management commands
             # that check for existing users.
             python manage.py createsuperuser --noinput --email admin@kmdiscova.com --user_type Admin || true &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin123456
      - HTTPS_ENABLED=True
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - kmdiscova-network
    healthcheck: # ADD THIS HEALTHCHECK
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"] # Assuming you have a /health/ endpoint
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s # Give it some time to start up before checking

  nginx:
    image: nginx:alpine
    container_name: kmdiscova-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      app:
        condition: service_healthy # CHANGE DEPENDS_ON TO USE HEALTHCHECK
    restart: unless-stopped
    networks:
      - kmdiscova-network

  certbot:
    image: certbot/certbot
    container_name: kmdiscova-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    networks:
      - kmdiscova-network # This was fixed, good!

networks:
  kmdiscova-network:
    driver: bridge

volumes:
  static_volume:
  media_volume: