services:
  app:
    build:
      context: .
      args:
        - DEV=false
    container_name: kmdiscova-app-prod
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "DJANGO_SETTINGS_MODULE=app.settings.production python manage.py wait_for_db &&
             DJANGO_SETTINGS_MODULE=app.settings.production python manage.py migrate &&
             DJANGO_SETTINGS_MODULE=app.settings.production python manage.py collectstatic --noinput &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.production
    restart: unless-stopped
    networks:
      - kmdiscova-prod

  nginx:
    image: nginx:alpine
    container_name: kmdiscova-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - kmdiscova-prod

networks:
  kmdiscova-prod:
    driver: bridge

volumes:
  static_volume:
  media_volume: