version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DEV=false
    container_name: kmdiscova-api-prod
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput --email admin@kmdiscova.com || true &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    env_file:
      - .env.prod
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin123456
    restart: unless-stopped
    networks:
      - kmdiscova-network

  nginx:
    image: nginx:alpine
    container_name: kmdiscova-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.api.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - kmdiscova-network

networks:
  kmdiscova-network:
    driver: bridge

volumes:
  static_volume:
  media_volume: