# Generated by Django 5.1.9 on 2025-06-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google account identifier for OAuth authentication', max_length=255, null=True, unique=True, verbose_name='google id'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['google_id'], name='users_google__d35fe6_idx'),
        ),
    ]
