# Generated by Django 5.1.9 on 2025-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_google_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, help_text='Facebook account identifier for OAuth authentication', max_length=255, null=True, unique=True, verbose_name='facebook id'),
        ),
    ]
