# Generated by Django 5.1.9 on 2025-06-24 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('psychologists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the cart', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(help_text='User who owns this cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the cart item', primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('OnlineMeeting', 'Online Session - 1 hour'), ('InitialConsultation', 'Initial Consultation - 2 hours (In-Person)')], help_text='Type of session: online or in-person consultation', max_length=20, verbose_name='session type')),
                ('start_slot_id', models.IntegerField(help_text='ID of the first slot to book (for consecutive booking)', verbose_name='start slot ID')),
                ('scheduled_start_time', models.DateTimeField(help_text='When the session is scheduled to start', verbose_name='scheduled start time')),
                ('scheduled_end_time', models.DateTimeField(help_text='When the session is scheduled to end', verbose_name='scheduled end time')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this booking', max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3, verbose_name='currency')),
                ('parent_notes', models.TextField(blank=True, help_text='Notes from parent about the booking', verbose_name='parent notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional booking metadata', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cart', models.ForeignKey(help_text='Cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('child', models.ForeignKey(help_text='Child this booking is for', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='children.child')),
                ('psychologist', models.ForeignKey(help_text='Psychologist for the booking', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='psychologists.psychologist')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='carts_user_id_b1c689_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at'], name='carts_created_22c862_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='carts_updated_d6666c_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_items_cart_id_3caa7d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['child'], name='cart_items_child_i_de8535_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['psychologist'], name='cart_items_psychol_206221_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['session_type'], name='cart_items_session_3e5410_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['scheduled_start_time'], name='cart_items_schedul_472d05_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['start_slot_id'], name='cart_items_start_s_54e4db_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['created_at'], name='cart_items_created_71da0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'child', 'psychologist', 'start_slot_id'), name='unique_cart_booking_per_child_psychologist_slot'),
        ),
    ]
