# Generated by Django 5.1.9 on 2025-05-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='qr_verification_code',
            field=models.CharField(blank=True, help_text='QR code for verifying in-person session attendance', max_length=32, null=True, unique=True, verbose_name='QR verification code'),
        ),
    ]
