# Generated by Django 5.1.9 on 2025-05-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(choices=[('OnlineMeeting', 'Online Session - 1 hour'), ('InitialConsultation', 'Initial Consultation - 2 hours (In-Person)')], help_text='Type of session: online or in-person consultation', max_length=20, verbose_name='session type'),
        ),
    ]
