# Generated by Django 5.1.9 on 2025-06-06 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_session_type'),
        ('psychologists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='reservation_status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved During Payment')], default='available', help_text='Temporary reservation status during payment process', max_length=20, verbose_name='reservation status'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='reserved_by',
            field=models.ForeignKey(blank=True, help_text='User who has temporarily reserved this slot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='reserved_until',
            field=models.DateTimeField(blank=True, help_text='When the temporary reservation expires', null=True, verbose_name='reserved until'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Payment_Pending', 'Payment Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No_Show', 'No Show'), ('Payment_Failed', 'Payment Failed')], default='Payment_Pending', help_text='Current status of the appointment', max_length=20, verbose_name='appointment status'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['reservation_status', 'reserved_until'], name='appointment_reserva_072b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['reserved_by', 'reservation_status'], name='appointment_reserve_7648a1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['psychologist', 'is_booked', 'reservation_status'], name='appointment_psychol_7a1120_idx'),
        ),
    ]
