# Generated by Django 5.1.9 on 2025-06-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointmentslot_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Payment_Pending', 'Payment Pending'), ('Scheduled', 'Scheduled'), ('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No_Show', 'No Show'), ('Payment_Failed', 'Payment Failed')], default='Payment_Pending', help_text='Current status of the appointment', max_length=20, verbose_name='appointment status'),
        ),
    ]
