# Generated by Django 5.1.9 on 2025-06-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the appointment (e.g., Zoom details)', null=True, verbose_name='metadata'),
        ),
    ]
