# Generated by Django 5.1.9 on 2025-06-19 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_add_metadata_for_zoom'),
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_verified_by',
            field=models.ForeignKey(blank=True, help_text='Psychologist who performed the verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sessions', to='psychologists.psychologist'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='session_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when session was verified via face scan', null=True, verbose_name='session verified at'),
        ),
    ]
