# Generated by Django 5.1.9 on 2025-05-25 04:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(help_text='Link to the base user account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(help_text="Parent's first name", max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(help_text="Parent's last name", max_length=100, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('address_line1', models.CharField(blank=True, help_text='Street address, P.O. box, company name, c/o', max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, help_text='City or town', max_length=100, verbose_name='city')),
                ('state_province', models.CharField(blank=True, help_text='State, province, or region', max_length=100, verbose_name='state/province')),
                ('postal_code', models.CharField(blank=True, help_text='ZIP or postal code', max_length=20, verbose_name='postal code')),
                ('country', models.CharField(blank=True, default='US', help_text='Country', max_length=50, verbose_name='country')),
                ('communication_preferences', models.JSONField(blank=True, default=dict, help_text='Notification and communication preferences', verbose_name='communication preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'db_table': 'parents',
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='parents_first_n_277e3b_idx'), models.Index(fields=['city', 'state_province'], name='parents_city_51505b_idx'), models.Index(fields=['created_at'], name='parents_created_c248cf_idx')],
            },
        ),
    ]
