# Generated by Django 5.1.9 on 2025-06-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_alter_parent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='face_embedding',
            field=models.BinaryField(blank=True, help_text='Facial recognition embedding for session verification', null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='face_embedding_created_at',
            field=models.DateTimeField(blank=True, help_text='When the face embedding was last generated', null=True),
        ),
    ]
