# Generated by Django 5.1.9 on 2025-06-21 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_parent_face_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['face_embedding_created_at'], name='parents_face_em_1cb21b_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['user', 'face_embedding'], name='parents_user_id_ec845b_idx'),
        ),
    ]
