# Generated by Django 5.1.9 on 2025-06-06 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointmentslot_reservation_status_and_more'),
        ('payments', '0001_initial'),
        ('psychologists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='appointment_order_has_psychologist_and_appointment',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('order_type', 'psychologist_registration'), ('psychologist__isnull', False), _connector='OR'), name='appointment_order_has_psychologist'),
        ),
    ]
