# Generated by Django 5.1.9 on 2025-05-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistavailability',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='Day of the week (0=Sunday, 1=Monday, etc.)', null=True, verbose_name='day of week'),
        ),
    ]
