# app/appointments/tests/test_views_face_verification.py

import io
import uuid
from datetime import date, timedelta
from unittest.mock import patch

from PIL import Image
from django.urls import reverse
from django.utils import timezone
from rest_framework import status
from rest_framework.test import APITestCase

from appointments.models import Appointment
from appointments.services import (
    FaceVerificationService,
    NoFaceDetectedError,
    ParentEmbeddingNotFoundError,
    FaceVerificationError
)
from children.models import Child
from parents.models import Parent
from psychologists.models import Psychologist
from users.models import User


class AppointmentVerifyFaceAPITest(APITestCase):
    """
    Test cases for the 'verify_face' action in the AppointmentViewSet.
    """

    @classmethod
    def setUpTestData(cls):
        """Set up data for the entire test case class."""
        # Create a psychologist user
        cls.psychologist_user = User.objects.create_user(
            email="psychologist_face_test@example.com",
            password="testpassword",
            user_type="Psychologist",
            is_verified=True,
        )
        cls.psychologist = Psychologist.objects.create(
            user=cls.psychologist_user,
            first_name='Jane',
            last_name='Smith',
            license_number='PSY12345',
            license_issuing_authority='State Board',
            license_expiry_date=date.today() + timedelta(days=365),
            years_of_experience=10,
            verification_status='Approved',
            offers_online_sessions=True,
            offers_initial_consultation=True,
            office_address='123 Main St, City, State'
        )

        # Create a parent user with a face embedding
        cls.parent_user = User.objects.create_user(
            email="parent_verify_face@example.com",
            password="testpassword",
            user_type="Parent",
            is_verified=True,
        )
        cls.parent = Parent.objects.get(user=cls.parent_user)
        cls.parent.face_embedding = b'fake-embedding-data'
        cls.parent.save()

        # Create a child
        cls.child = Child.objects.create(
            parent=cls.parent,
            first_name="Face Test Child",
            date_of_birth=date(2020, 1, 1),
        )

        # Create a valid 'InitialConsultation' appointment
        cls.initial_consultation = Appointment.objects.create(
            psychologist=cls.psychologist,
            parent=cls.parent,
            child=cls.child,
            session_type="InitialConsultation",
            appointment_status="Scheduled",
            scheduled_start_time=timezone.now() + timedelta(minutes=10),
            scheduled_end_time=timezone.now() + timedelta(hours=2),
        )

        # Create an 'OnlineMeeting' appointment to test incorrect session type
        cls.online_meeting = Appointment.objects.create(
            psychologist=cls.psychologist,
            parent=cls.parent,
            child=cls.child,
            session_type="OnlineMeeting",
            appointment_status="Scheduled",
            scheduled_start_time=timezone.now() + timedelta(days=1),
            scheduled_end_time=timezone.now() + timedelta(days=1, hours=1),
        )

        # The correct URL name as generated by DRF's DefaultRouter
        cls.url_name = "appointment-verify-face"

    def _get_url(self, appointment_pk):
        """Helper to generate the URL for the verify_face action."""
        return reverse(self.url_name, kwargs={"pk": appointment_pk})

    def _create_dummy_image_file(self):
        """Creates a dummy image file in memory for multipart form upload."""
        buffer = io.BytesIO()
        Image.new("RGB", (100, 100), color="purple").save(buffer, "jpeg")
        buffer.seek(0)
        file_like_object = io.BytesIO(buffer.getvalue())
        file_like_object.name = "face.jpg"
        return file_like_object

    @patch("appointments.views.FaceVerificationService.verify_parent_for_session")
    def test_verify_face_success(self, mock_verify_service):
        """
        Test successful face verification for an InitialConsultation.
        """
        # Arrange
        self.client.force_authenticate(user=self.psychologist_user)

        # This is the expected successful return value from the service
        mock_verify_service.return_value = {
            "is_match": True,
            "confidence_score": 0.98,
            "parent_name": "Test Parent"
        }

        # Refresh the appointment object before using it to set expectations
        self.initial_consultation.refresh_from_db()

        url = self._get_url(self.initial_consultation.appointment_id)
        image_file = self._create_dummy_image_file()
        data = {"image": image_file}

        # Act
        response = self.client.post(url, data, format="multipart")

        # Assert
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["status"], "success")
        self.assertEqual(response.data["message"], "Face verification successful. Session started.")
        self.assertEqual(response.data["appointment_status"], "In_Progress")
        self.assertIn("actual_start_time", response.data)

        # Ensure the service was called correctly
        mock_verify_service.assert_called_once()
        called_appointment, called_image_data = mock_verify_service.call_args[0]
        self.assertEqual(called_appointment.appointment_id, self.initial_consultation.appointment_id)
        self.assertIsInstance(called_image_data, bytes)

    @patch("appointments.views.FaceVerificationService.verify_parent_for_session")
    def test_verify_face_not_recognized(self, mock_verify_service):
        """
        Test failed verification when the face does not match.
        """
        # Arrange
        self.client.force_authenticate(user=self.psychologist_user)
        mock_verify_service.return_value = {
            "is_match": False,
            "confidence_score": 0.21,
        }
        url = self._get_url(self.initial_consultation.appointment_id)
        data = {"image": self._create_dummy_image_file()}

        # Act
        response = self.client.post(url, data, format="multipart")

        # Assert
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["status"], "failure")
        self.assertEqual(response.data["error_code"], "FACE_NOT_RECOGNIZED")
        self.assertEqual(response.data["message"], "Face not recognized. Please ensure this is the correct parent.")

    @patch("appointments.views.FaceVerificationService.verify_parent_for_session", side_effect=NoFaceDetectedError)
    def test_verify_face_no_face_detected_error(self, mock_verify_service):
        """
        Test the error response when the service raises NoFaceDetectedError.
        """
        # Arrange
        self.client.force_authenticate(user=self.psychologist_user)
        url = self._get_url(self.initial_consultation.appointment_id)
        data = {"image": self._create_dummy_image_file()}

        # Act
        response = self.client.post(url, data, format="multipart")

        # Assert
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["status"], "failure")
        self.assertEqual(response.data["error_code"], "NO_FACE_DETECTED")
        self.assertEqual(response.data["message"], "No face detected in the image. Please ensure the parent is clearly visible.")

    @patch("appointments.views.FaceVerificationService.verify_parent_for_session", side_effect=ParentEmbeddingNotFoundError)
    def test_verify_face_no_embedding_error(self, mock_verify_service):
        """
        Test the error response when the parent has no stored face embedding.
        """
        # Arrange
        self.client.force_authenticate(user=self.psychologist_user)
        url = self._get_url(self.initial_consultation.appointment_id)
        data = {"image": self._create_dummy_image_file()}

        # Act
        response = self.client.post(url, data, format="multipart")

        # Assert
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["status"], "failure")
        self.assertEqual(response.data["error_code"], "NO_EMBEDDING")
        self.assertEqual(response.data["message"], "Parent does not have a face embedding. Please ask them to update their profile picture.")

    def test_verify_face_on_wrong_session_type(self):
        """
        Test that verify_face fails for appointments that are not 'InitialConsultation'.
        """
        # Arrange
        self.client.force_authenticate(user=self.psychologist_user)
        url = self._get_url(self.online_meeting.appointment_id)
        data = {"image": self._create_dummy_image_file()}

        # Act
        response = self.client.post(url, data, format="multipart")

        # Assert
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["status"], "failure")
        self.assertEqual(response.data["error_code"], "INVALID_SESSION_TYPE")

    def test_verify_face_on_completed_appointment(self):
        """
        Test that verify_face fails for appointments not in 'Scheduled' status.
        """
        # Arrange
        self.client.force_authenticate(user=self.psychologist_user)
        self.initial_consultation.appointment_status = "Completed"
        self.initial_consultation.save()
        url = self._get_url(self.initial_consultation.appointment_id)
        data = {"image": self._create_dummy_image_file()}

        # Act
        response = self.client.post(url, data, format="multipart")

        # Assert
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["status"], "failure")
        self.assertEqual(response.data["error_code"], "INVALID_STATUS")

    def test_verify_face_unauthenticated(self):
        """
        Test that an unauthenticated request is rejected.
        """
        # Arrange
        url = self._get_url(self.initial_consultation.appointment_id)
        data = {"image": self._create_dummy_image_file()}

        # Act
        response = self.client.post(url, data, format="multipart")

        # Assert
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)