---
name: Checks

on: [push]

jobs:
    test:
        name: Test

        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Test
              env:
                DEBUG: False
                DB_HOST: localhost
                DB_NAME: devdb
                DB_USER: devuser
                DB_PASSWORD: changeme
                SECRET_KEY: test-secret-key-for-ci
                EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
                ALLOWED_HOSTS: localhost,127.0.0.1
              run: docker compose run --rm app ash -c "python manage.py wait_for_db && python manage.py test"