---
name: Checks

on: [push]

jobs:
    test:
        name: Test

        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Test
              env:
                DEBUG: False
                DB_HOST: db
                DB_NAME: devdb
                DB_USER: devuser
                DB_PASSWORD: changeme
                SECRET_KEY: test-secret-key-for-ci
                EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
                ALLOWED_HOSTS: localhost,127.0.0.1
                # Email settings (have defaults but good to be explicit)
                EMAIL_HOST: ""
                EMAIL_PORT: 587
                EMAIL_USE_TLS: True
                EMAIL_HOST_USER: ""
                EMAIL_HOST_PASSWORD: ""
                DEFAULT_FROM_EMAIL: "K&Mdiscova <noreply@kmdiscova.com>"
                # Frontend URL for tests
                FRONTEND_URL: "http://localhost:8000"
                # Support email
                SUPPORT_EMAIL: "support@kmdiscova.com"
                COMPANY_ADDRESS: ""
              run: docker compose run --rm app ash -c "python manage.py wait_for_db && python manage.py test"