---
name: Checks

on: [push]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Test
              env:
                # Use development settings for testing
                DJANGO_SETTINGS_MODULE: app.settings.development
                DEBUG: True

                # Test database configuration (local PostgreSQL for CI)
                DB_HOST: db
                DB_NAME: testdb
                DB_USER: testuser
                DB_PASSWORD: testpass
                DB_PORT: 5432
                DB_SSL_MODE: disable

                # Security
                SECRET_KEY: test-secret-key-for-ci-very-long-and-secure
                ALLOWED_HOSTS: localhost,127.0.0.1,testserver

                # Email settings for testing
                EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend
                EMAIL_HOST: ""
                EMAIL_PORT: 587
                EMAIL_USE_TLS: True
                EMAIL_HOST_USER: ""
                EMAIL_HOST_PASSWORD: ""
                DEFAULT_FROM_EMAIL: "K&Mdiscova Test <noreply@test.com>"

                # Frontend URL for tests
                FRONTEND_URL: "http://localhost:8000"

                # Support settings
                SUPPORT_EMAIL: "support@test.com"
                COMPANY_ADDRESS: "Test Address"

                # Additional test settings
                EMAIL_VERIFICATION_TIMEOUT_DAYS: 3
              run: |
                docker compose -f docker-compose.test.yml run --rm app sh -c "
                  python manage.py wait_for_db &&
                  python manage.py migrate &&
                  python manage.py test
                "